name: drawing_application
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  injectable: ^2.4.4
  get_it: ^7.7.0
  auto_route: ^9.2.2
  injectable_generator: ^2.6.2
  auto_route_generator: ^9.0.0
  elementary: ^3.1.1
  flutter_bounceable: ^1.1.0
  freezed_annotation: ^2.4.4

dev_dependencies:
  build_runner: ^2.4.11
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  freezed: ^2.5.2

flutter:
  uses-material-design: true
